sudo: true
dist: xenial

jobs:
  include:
    # artifacts do not persist between jobs so everything executed in single stage
    - stage: test
      script:
      # generate
      - docker build -t duktape-webgl-generator -f generator/Dockerfile .
      - docker run -t --read-only duktape-webgl-generator > examples/00_bootstrap/dukwebgl.h
      # compile
      - docker build -t duktape-webgl-examples examples
      # test
      - docker run --rm -t duktape-webgl-examples
